const mongoose = require('mongoose');
const Enrollment = require('./models/enrollment');

const testEnrollments = [
  {
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@email.com',
    phone: '555-0101',
    address: '123 Main St, New York, NY 10001',
    city: 'New York',
    state: 'NY',
    zipCode: '10001',
    country: 'USA',
    sponsorId: 'SP001',
    sponsorName: 'Jane Doe',
    sponsorEmail: 'jane.doe@email.com',
    sponsorPhone: '555-0102',
    package: 'Business Builder',
    paymentMethod: 'Credit Card',
    status: 'Active',
    enrollmentDate: new Date('2024-03-01')
  },
  {
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.j@email.com',
    phone: '555-0103',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90001',
    country: 'USA',
    sponsorId: 'SP002',
    sponsorName: 'Mike Wilson',
    sponsorEmail: 'mike.w@email.com',
    sponsorPhone: '555-0104',
    package: 'Professional',
    paymentMethod: 'Bank Transfer',
    status: 'Active',
    enrollmentDate: new Date('2024-03-02')
  },
  {
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael.b@email.com',
    phone: '555-0105',
    address: '789 Pine Rd, Chicago, IL 60601',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60601',
    country: 'USA',
    sponsorId: 'SP003',
    sponsorName: 'Lisa Anderson',
    sponsorEmail: 'lisa.a@email.com',
    sponsorPhone: '555-0106',
    package: 'Business Builder',
    paymentMethod: 'Credit Card',
    status: 'Pending',
    enrollmentDate: new Date('2024-03-03')
  },
  {
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.d@email.com',
    phone: '555-0107',
    address: '321 Elm St, Houston, TX 77001',
    city: 'Houston',
    state: 'TX',
    zipCode: '77001',
    country: 'USA',
    sponsorId: 'SP004',
    sponsorName: 'David Lee',
    sponsorEmail: 'david.l@email.com',
    sponsorPhone: '555-0108',
    package: 'Professional',
    paymentMethod: 'Bank Transfer',
    status: 'Active',
    enrollmentDate: new Date('2024-03-04')
  },
  {
    firstName: 'Robert',
    lastName: 'Wilson',
    email: 'robert.w@email.com',
    phone: '555-0109',
    address: '654 Maple Dr, Phoenix, AZ 85001',
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '85001',
    country: 'USA',
    sponsorId: 'SP005',
    sponsorName: 'Jennifer Taylor',
    sponsorEmail: 'jennifer.t@email.com',
    sponsorPhone: '555-0110',
    package: 'Business Builder',
    paymentMethod: 'Credit Card',
    status: 'Active',
    enrollmentDate: new Date('2024-03-05')
  },
  {
    firstName: 'Lisa',
    lastName: 'Anderson',
    email: 'lisa.a@email.com',
    phone: '555-0111',
    address: '987 Cedar Ln, Philadelphia, PA 19101',
    city: 'Philadelphia',
    state: 'PA',
    zipCode: '19101',
    country: 'USA',
    sponsorId: 'SP006',
    sponsorName: 'Thomas Moore',
    sponsorEmail: 'thomas.m@email.com',
    sponsorPhone: '555-0112',
    package: 'Professional',
    paymentMethod: 'Bank Transfer',
    status: 'Pending',
    enrollmentDate: new Date('2024-03-06')
  },
  {
    firstName: 'David',
    lastName: 'Lee',
    email: 'david.l@email.com',
    phone: '555-0113',
    address: '147 Birch St, San Antonio, TX 78201',
    city: 'San Antonio',
    state: 'TX',
    zipCode: '78201',
    country: 'USA',
    sponsorId: 'SP007',
    sponsorName: 'Patricia White',
    sponsorEmail: 'patricia.w@email.com',
    sponsorPhone: '555-0114',
    package: 'Business Builder',
    paymentMethod: 'Credit Card',
    status: 'Active',
    enrollmentDate: new Date('2024-03-07')
  },
  {
    firstName: 'Jennifer',
    lastName: 'Taylor',
    email: 'jennifer.t@email.com',
    phone: '555-0115',
    address: '258 Willow Ave, San Diego, CA 92101',
    city: 'San Diego',
    state: 'CA',
    zipCode: '92101',
    country: 'USA',
    sponsorId: 'SP008',
    sponsorName: 'James Brown',
    sponsorEmail: 'james.b@email.com',
    sponsorPhone: '555-0116',
    package: 'Professional',
    paymentMethod: 'Bank Transfer',
    status: 'Active',
    enrollmentDate: new Date('2024-03-08')
  },
  {
    firstName: 'Thomas',
    lastName: 'Moore',
    email: 'thomas.m@email.com',
    phone: '555-0117',
    address: '369 Spruce Rd, Dallas, TX 75201',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75201',
    country: 'USA',
    sponsorId: 'SP009',
    sponsorName: 'Mary Johnson',
    sponsorEmail: 'mary.j@email.com',
    sponsorPhone: '555-0118',
    package: 'Business Builder',
    paymentMethod: 'Credit Card',
    status: 'Active',
    enrollmentDate: new Date('2024-03-09')
  },
  {
    firstName: 'Patricia',
    lastName: 'White',
    email: 'patricia.w@email.com',
    phone: '555-0119',
    address: '741 Ash Dr, San Jose, CA 95101',
    city: 'San Jose',
    state: 'CA',
    zipCode: '95101',
    country: 'USA',
    sponsorId: 'SP010',
    sponsorName: 'Robert Davis',
    sponsorEmail: 'robert.d@email.com',
    sponsorPhone: '555-0120',
    package: 'Professional',
    paymentMethod: 'Bank Transfer',
    status: 'Pending',
    enrollmentDate: new Date('2024-03-10')
  },
  {
    firstName: 'James',
    lastName: 'Brown',
    email: 'james.b@email.com',
    phone: '555-0121',
    address: '852 Poplar St, Austin, TX 78701',
    city: 'Austin',
    state: 'TX',
    zipCode: '78701',
    country: 'USA',
    sponsorId: 'SP011',
    sponsorName: 'Linda Wilson',
    sponsorEmail: 'linda.w@email.com',
    sponsorPhone: '555-0122',
    package: 'Business Builder',
    paymentMethod: 'Credit Card',
    status: 'Active',
    enrollmentDate: new Date('2024-03-11')
  },
  {
    firstName: 'Mary',
    lastName: 'Johnson',
    email: 'mary.j@email.com',
    phone: '555-0123',
    address: '963 Pinecone Ln, Jacksonville, FL 32201',
    city: 'Jacksonville',
    state: 'FL',
    zipCode: '32201',
    country: 'USA',
    sponsorId: 'SP012',
    sponsorName: 'William Anderson',
    sponsorEmail: 'william.a@email.com',
    sponsorPhone: '555-0124',
    package: 'Professional',
    paymentMethod: 'Bank Transfer',
    status: 'Active',
    enrollmentDate: new Date('2024-03-12')
  },
  {
    firstName: 'Robert',
    lastName: 'Davis',
    email: 'robert.d@email.com',
    phone: '555-0125',
    address: '159 Oakwood Dr, Fort Worth, TX 76101',
    city: 'Fort Worth',
    state: 'TX',
    zipCode: '76101',
    country: 'USA',
    sponsorId: 'SP013',
    sponsorName: 'Elizabeth Taylor',
    sponsorEmail: 'elizabeth.t@email.com',
    sponsorPhone: '555-0126',
    package: 'Business Builder',
    paymentMethod: 'Credit Card',
    status: 'Active',
    enrollmentDate: new Date('2024-03-13')
  },
  {
    firstName: 'Linda',
    lastName: 'Wilson',
    email: 'linda.w@email.com',
    phone: '555-0127',
    address: '267 Maplewood Ave, Columbus, OH 43201',
    city: 'Columbus',
    state: 'OH',
    zipCode: '43201',
    country: 'USA',
    sponsorId: 'SP014',
    sponsorName: 'Joseph Moore',
    sponsorEmail: 'joseph.m@email.com',
    sponsorPhone: '555-0128',
    package: 'Professional',
    paymentMethod: 'Bank Transfer',
    status: 'Pending',
    enrollmentDate: new Date('2024-03-14')
  },
  {
    firstName: 'William',
    lastName: 'Anderson',
    email: 'william.a@email.com',
    phone: '555-0129',
    address: '378 Birchwood Rd, Charlotte, NC 28201',
    city: 'Charlotte',
    state: 'NC',
    zipCode: '28201',
    country: 'USA',
    sponsorId: 'SP015',
    sponsorName: 'Margaret White',
    sponsorEmail: 'margaret.w@email.com',
    sponsorPhone: '555-0130',
    package: 'Business Builder',
    paymentMethod: 'Credit Card',
    status: 'Active',
    enrollmentDate: new Date('2024-03-15')
  },
  {
    firstName: 'Elizabeth',
    lastName: 'Taylor',
    email: 'elizabeth.t@email.com',
    phone: '555-0131',
    address: '489 Cedarwood St, Indianapolis, IN 46201',
    city: 'Indianapolis',
    state: 'IN',
    zipCode: '46201',
    country: 'USA',
    sponsorId: 'SP016',
    sponsorName: 'Richard Brown',
    sponsorEmail: 'richard.b@email.com',
    sponsorPhone: '555-0132',
    package: 'Professional',
    paymentMethod: 'Bank Transfer',
    status: 'Active',
    enrollmentDate: new Date('2024-03-16')
  },
  {
    firstName: 'Joseph',
    lastName: 'Moore',
    email: 'joseph.m@email.com',
    phone: '555-0133',
    address: '591 Sprucewood Ln, Seattle, WA 98101',
    city: 'Seattle',
    state: 'WA',
    zipCode: '98101',
    country: 'USA',
    sponsorId: 'SP017',
    sponsorName: 'Susan Davis',
    sponsorEmail: 'susan.d@email.com',
    sponsorPhone: '555-0134',
    package: 'Business Builder',
    paymentMethod: 'Credit Card',
    status: 'Active',
    enrollmentDate: new Date('2024-03-17')
  },
  {
    firstName: 'Margaret',
    lastName: 'White',
    email: 'margaret.w@email.com',
    phone: '555-0135',
    address: '693 Pinewood Dr, Denver, CO 80201',
    city: 'Denver',
    state: 'CO',
    zipCode: '80201',
    country: 'USA',
    sponsorId: 'SP018',
    sponsorName: 'Thomas Johnson',
    sponsorEmail: 'thomas.j@email.com',
    sponsorPhone: '555-0136',
    package: 'Professional',
    paymentMethod: 'Bank Transfer',
    status: 'Pending',
    enrollmentDate: new Date('2024-03-18')
  },
  {
    firstName: 'Richard',
    lastName: 'Brown',
    email: 'richard.b@email.com',
    phone: '555-0137',
    address: '795 Oakwood Ave, Washington, DC 20001',
    city: 'Washington',
    state: 'DC',
    zipCode: '20001',
    country: 'USA',
    sponsorId: 'SP019',
    sponsorName: 'Nancy Wilson',
    sponsorEmail: 'nancy.w@email.com',
    sponsorPhone: '555-0138',
    package: 'Business Builder',
    paymentMethod: 'Credit Card',
    status: 'Active',
    enrollmentDate: new Date('2024-03-19')
  },
  {
    firstName: 'Susan',
    lastName: 'Davis',
    email: 'susan.d@email.com',
    phone: '555-0139',
    address: '897 Maplewood Rd, Boston, MA 02101',
    city: 'Boston',
    state: 'MA',
    zipCode: '02101',
    country: 'USA',
    sponsorId: 'SP020',
    sponsorName: 'Paul Anderson',
    sponsorEmail: 'paul.a@email.com',
    sponsorPhone: '555-0140',
    package: 'Professional',
    paymentMethod: 'Bank Transfer',
    status: 'Active',
    enrollmentDate: new Date('2024-03-20')
  },
  {
    firstName: 'Thomas',
    lastName: 'Johnson',
    email: 'thomas.j@email.com',
    phone: '555-0141',
    address: '912 Birchwood St, Nashville, TN 37201',
    city: 'Nashville',
    state: 'TN',
    zipCode: '37201',
    country: 'USA',
    sponsorId: 'SP021',
    sponsorName: 'Betty Taylor',
    sponsorEmail: 'betty.t@email.com',
    sponsorPhone: '555-0142',
    package: 'Business Builder',
    paymentMethod: 'Credit Card',
    status: 'Active',
    enrollmentDate: new Date('2024-03-21')
  },
  {
    firstName: 'Nancy',
    lastName: 'Wilson',
    email: 'nancy.w@email.com',
    phone: '555-0143',
    address: '123 Cedarwood Ln, Portland, OR 97201',
    city: 'Portland',
    state: 'OR',
    zipCode: '97201',
    country: 'USA',
    sponsorId: 'SP022',
    sponsorName: 'George Moore',
    sponsorEmail: 'george.m@email.com',
    sponsorPhone: '555-0144',
    package: 'Professional',
    paymentMethod: 'Bank Transfer',
    status: 'Pending',
    enrollmentDate: new Date('2024-03-22')
  },
  {
    firstName: 'Paul',
    lastName: 'Anderson',
    email: 'paul.a@email.com',
    phone: '555-0145',
    address: '234 Sprucewood Dr, Oklahoma City, OK 73101',
    city: 'Oklahoma City',
    state: 'OK',
    zipCode: '73101',
    country: 'USA',
    sponsorId: 'SP023',
    sponsorName: 'Helen White',
    sponsorEmail: 'helen.w@email.com',
    sponsorPhone: '555-0146',
    package: 'Business Builder',
    paymentMethod: 'Credit Card',
    status: 'Active',
    enrollmentDate: new Date('2024-03-23')
  },
  {
    firstName: 'Betty',
    lastName: 'Taylor',
    email: 'betty.t@email.com',
    phone: '555-0147',
    address: '345 Pinewood Ave, Las Vegas, NV 89101',
    city: 'Las Vegas',
    state: 'NV',
    zipCode: '89101',
    country: 'USA',
    sponsorId: 'SP024',
    sponsorName: 'Edward Brown',
    sponsorEmail: 'edward.b@email.com',
    sponsorPhone: '555-0148',
    package: 'Professional',
    paymentMethod: 'Bank Transfer',
    status: 'Active',
    enrollmentDate: new Date('2024-03-24')
  },
  {
    firstName: 'George',
    lastName: 'Moore',
    email: 'george.m@email.com',
    phone: '555-0149',
    address: '456 Oakwood Rd, Louisville, KY 40201',
    city: 'Louisville',
    state: 'KY',
    zipCode: '40201',
    country: 'USA',
    sponsorId: 'SP025',
    sponsorName: 'Sharon Davis',
    sponsorEmail: 'sharon.d@email.com',
    sponsorPhone: '555-0150',
    package: 'Business Builder',
    paymentMethod: 'Credit Card',
    status: 'Active',
    enrollmentDate: new Date('2024-03-25')
  }
];

const seedDatabase = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect('mongodb://localhost:27017/talkfusion_enrollment', {
      useNewUrlParser: true,
      useUnifiedTopology: true
    });

    // Clear existing enrollments
    await Enrollment.deleteMany({});
    console.log('Cleared existing enrollments');

    // Insert test enrollments
    const result = await Enrollment.insertMany(testEnrollments);
    console.log(`Successfully inserted ${result.length} test enrollments`);

    // Close the connection
    await mongoose.connection.close();
    console.log('Database connection closed');
  } catch (error) {
    console.error('Error seeding database:', error);
  }
};

// Run the seed function
seedDatabase(); 